name: ASV Benchmarking

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      CONDA_ENV_FILE: ./build_envs/asv-bench.yml
      ASV_DIR: ./benchmarks

    steps:
      - name: Checkout geocat-comp
        uses: actions/checkout@v4
        with:
          repository: NCAR/geocat-comp
          fetch-depth: 0
      - name: Checkout geocat-comp-asv
        uses: actions/checkout@v4
        with:
          repository: anissa111/geocat-comp-asv
          persist-credentials: false
          fetch-depth: 0
          ref: main
          path: geocat-comp-asv
      - name: Set environment variables
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ./build_envs/asv-bench.yml
          environment-name: asv-bench
          cache-environment: true
          cache-environment-key: "benchmark-${{runner.os}}-${{runner.arch}}-${{env.TODAY}}"

      - name: Copy existing results
        run: |
          cp -r geocat-comp-asv/results benchmarks/results
          tree .

      - name: Run benchmarks
        shell: bash -l {0}
        id: benchmark
        run: |
          cd benchmarks
          asv machine --machine GH-Actions --os ubuntu-latest --arch x64 --cpu "2-core unknown" --ram 7GB
          asv run v2023.10.0..main --skip-existing-commits

      - name: Commit and push benchmark results
        run: |
          cp -r benchmarks/results geocat-comp-asv/results
          cd geocat-comp-asv
          git config --local user.email "anissaz@ucar.edu"
          git config --local user.name "anissa111"
          git add results
          git commit -m "Update benchmark results"

      - name: Push to geocat-comp-asv
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.COMP_ASV_PAT }}
          branch: main
          force: true
          repository: anissa111/geocat-comp-asv
          directory: geocat-comp-asv
